kind: pipeline
name: build

platform:
  os: linux
  arch: amd64

steps:
  - name: build-1.10
    image: gradle:jdk8
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    commands:
      - ln -s "$PWD/ForgeWurst MC 1.12.2/src/shared" "$PWD/ForgeWurst MC 1.10.2/src/shared"
      - cd "ForgeWurst MC 1.10.2/"
      - export GRADLE_USER_HOME="$PWD/.gradle"
      - ./gradlew build

  - name: build-1.12
    image: gradle:jdk8
    environment:
      GRADLE_OPTS: "-Dorg.gradle.daemon=false"
    commands:
      - cd "ForgeWurst MC 1.12.2/"
      - export GRADLE_USER_HOME="$PWD/.gradle"
      - ./gradlew build

  - name: release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: GITHUB_KEY
      files:
        - ForgeWurst MC 1.10.2/build/libs/*
        - ForgeWurst MC 1.12.2/build/libs/*
    when:
      event: tag
    depends_on:
      - build-1.10
      - build-1.12
